### ISSUE TITLE
关于《mysql 分表实践》这篇博客的几点疑问

### ISSUE THREAD

**Issue by xvrzhao** [ltinyho/ltinyho.github.io#1]
关于这篇博客 https://blog.ltinyho.top/2019/06/23/mysql-split-table/ 有几点疑问：

1. 大佬是如何保证大表数据能均匀分布到多个分表里的呢，文中说根据hashcode取余，但是hashcode不能保证得到的结果是连续的吧，那取余之后的结果也不是连续的了。
2. 不知大佬是如何解决分表之后，新数据的唯一主键的，虽然可以通过雪花算法生成全局唯一主键。但是老表肯定存在一个自增的ID主键列吧，分表里如果也有该字段，大佬是如何保证ID的全局连续性的？

先行感谢大佬回答！

**Comment by ltinyho** [comment]
你好。
第一问题：主键 id 用来取数据，hashcode 是根据 openid(微信 openid) 来取余的，同一个  openid 可以分到同一个表中，不同 openid 的数据量可能不同，只要同一个 openid 的数据在同一个表即可。文中没有写清楚。

ps: 用户的数据不多的话，有的用户数据多，有的用户数据少，不一定能保证数据的均匀性.

第二个问题： 跟第一问题相关，主键 id 每个表是单独递增的，需求上不需要保证全局的唯一主键，只需要保证每个 openid 对应的主键 id 递增即可。

漏掉了一些细节。

**Comment by xvrzhao** [comment]
感谢解答！
